version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: mango-detection-api
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend  # Changed from ./project/frontend
      dockerfile: Dockerfile
    container_name: mango-detection-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
